---
title: "Running Enformer across all rn7 genes"
author: "Sabrina Mi"
description: "Our pipeline inputs to run Enformer on the reference genome and sampled rat genotypes"
date: "8/10/23"
---

## Collect Gene Intervals

In [2]:
import pandas as pd
import random

In [3]:
# gene annotation
annot_df = pd.read_csv('/home/s1mi/enformer_rat_data/rn7.gene.txt', sep ='\t',  index_col='geneId')
annot_df.head(3)

/tmp/ipykernel_206323/2449699668.py:2: DtypeWarning: Columns (2) have mixed types. Specify dtype option on import or set low_memory=False.
  annot_df = pd.read_csv('/home/s1mi/enformer_rat_data/rn7.gene.txt', sep ='\t',  index_col='geneId')

,geneSymbol,chromosome,start,end,strand,tss,description,hasEqtl,expr_BLA,expr_Brain,...,sqtl_BLA,sqtl_Brain,sqtl_Eye,sqtl_IL,sqtl_LHb,sqtl_NAcc,sqtl_NAcc2,sqtl_OFC,sqtl_PL,sqtl_PL2
geneId,,,,,,,,,,,,,,,,,,,,,
ENSRNOG00000066169,ENSRNOG00000066169,1,36112690,36122387,-,36122387,NaN,True,True,True,...,False,False,False,False,False,False,False,False,False,False
ENSRNOG00000070168,Olr56,1,157231467,157232417,+,157231467,olfactory receptor family 51 subfamily F membe...,True,False,True,...,False,False,False,False,False,False,False,False,False,False
ENSRNOG00000070901,Irgq,1,80123925,80131881,+,80123925,immunity-related GTPase Q,True,True,True,...,False,False,False,False,False,False,False,False,False,False

In [4]:
obs_gene_expr = pd.read_csv("/home/s1mi/enformer_rat_data/Brain.rn7.expr.tpm.bed", sep="\t", header=0, index_col='gene_id')
obs_gene_expr.head()

/tmp/ipykernel_206323/3189498692.py:1: DtypeWarning: Columns (0) have mixed types. Specify dtype option on import or set low_memory=False.
  obs_gene_expr = pd.read_csv("/home/s1mi/enformer_rat_data/Brain.rn7.expr.tpm.bed", sep="\t", header=0, index_col='gene_id')

,#chr,start,end,000789972A,0007899884,000789FF64,00079298B1,00079299B5,0007929A79,0007929B36,...,0007899761,0007899866,00078A00E6,0007929938,0007929956,00079FF7D6,0007899826,0007929917,00077E82E3,00078A18A7
gene_id,,,,,,,,,,,,,,,,,,,,,
ENSRNOG00000065394,1,31563,31564,0.0,0.0,0.0,0.0,0.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0
ENSRNOG00000065356,1,41634,41635,0.0,0.0,0.0,0.0,0.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0
ENSRNOG00000070568,1,76833,76834,0.0,0.0,0.0,0.0,0.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.01,0.0,0.0,0.0,0.0
ENSRNOG00000065706,1,184235,184236,0.0,0.0,0.0,0.0,0.18,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0
ENSRNOG00000069644,1,272252,272253,0.0,0.0,0.0,0.0,0.00,0.0,0.0,...,0.0,0.0,0.0,0.0,0.0,0.00,0.0,0.0,0.0,0.0

In [7]:
obs_gene_expr['#chr'].unique()

array([1, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 2, 20, 3, 4, 5, 6, 7, 8,
       9, '9', 'JACYVU010000238.1', 'JACYVU010000315.1',
       'JACYVU010000319.1', 'JACYVU010000493.1', 'JACYVU010000587.1',
       'JACYVU010000589.1', 'JACYVU010000619.1', 'JACYVU010000634.1',
       'JACYVU010000642.1', 'JACYVU010000653.1', 'JACYVU010000665.1',
       'JACYVU010000706.1', 'JACYVU010000731.1', 'JACYVU010000732.1',
       'JACYVU010000738.1', 'JACYVU010000744.1', 'JACYVU010000754.1',
       'MT', 'MU150189.1', 'MU150193.1', 'MU150196.1', 'MU150200.1',
       'MU150203.1', 'MU150220.1', 'MU150222.1', 'MU150223.1', 'X', 'Y'],
      dtype=object)

We want to filter to genes on chromosome 1 through 20 and X and Y.

In [26]:
keys = ["1", "2", "3", "4", "5", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "X", "Y"]

with open("metadata/intervals.txt", "a") as f:
    for gene in obs_gene_expr.index:
        gene_annot = annot_df.loc[gene]
        chromosome = str(gene_annot['chromosome'])
        if chromosome in keys:
            tss = gene_annot['tss']
            interval = f"chr{chromosome}_{tss}_{tss}"
            f.write(interval + '\n')

### Sample Individuals

We "randomly" sampled three rats until we had a set that had at least some variety in color and sex.

In [ ]:
rat_info = pd.read_csv("/home/s1mi/enformer_rat_data/rn7.RatGTEx_rats.tsv", sep = "\t", index_col = "rat_id")
all_individuals = obs_gene_expr.columns.tolist()[3:]
sample = random.sample(all_individuals, 3)
rat_info.loc[sample]

            coatcolor tissues sex
rat_id
00079FE6B4  BLACKHOOD   Brain   F
0007899981  BROWNHOOD   Brain   M
00078A19B2      BROWN   Brain   M

In [ ]:
with open("metadata/individuals.txt", "a") as f:
    for individual in sample:
        f.write(individual + '\n')

## Run Enformer Pipeline


Run personalized for sampled rats:
```
module load conda

conda activate /lus/grand/projects/TFXcan/imlab/shared/software/conda_envs/enformer-predict-tools

cd /home/s1mi/Github/shared_pipelines/enformer_pipeline

python3 scripts/enformer_predict.py --parameters /home/s1mi/Github/deep-learning-in-genomics/posts/2023-08-10-correlation-across-genes/all_genes_personalized_config.json

```

Run on reference genome:

```
module load conda

conda activate /lus/grand/projects/TFXcan/imlab/shared/software/conda_envs/enformer-predict-tools

cd /home/s1mi/Github/shared_pipelines/enformer_pipeline

python3 scripts/enformer_predict.py --parameters /home/s1mi/Github/deep-learning-in-genomics/posts/2023-08-10-correlation-across-genes/all_genes_reference_config.json
```